### ISSUE TITLE
Update DataFusion dependency to 8.0.0

### ISSUE THREAD

**Issue by matthewmturner** [datafusion-contrib/datafusion-bigtable#4]

**Comment by jychen7** [comment]
@matthewmturner 
the `master` branch of Datafusion is not a static reference. As of 2022-06-26, latest version of Datafusion is 9.0.0.
Since 8.0.0 introduce some breaking change, how about we rename this issue to upgrade to datafusion 8.0.0?

after upgrade to 8.0.0 is done, create new issue for 9.0.0

**Comment by matthewmturner** [comment]
Yup fine with that. I think at the time I created this it was pre 8.0 release and I just wanted some of the bigger changes incorporated.

**Comment by jychen7** [comment]
btw, I create a PR #5 to upgrade to 8.0.0. Feel free to take a look if you have interest
